kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: postgres-perms
  namespace: kong
rules:
  - apiGroups:
    - ""
    resources:
    - secrets
    - services
    verbs:
    - patch
  - apiGroups:
    - apps
    resources:
    - statefulsets
    verbs:
    - patch
  - apiGroups:
    - security.openshift.io
    resourceNames:
    - anyuid
    resources:
    - securitycontextconstraints
    verbs:
    - use
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ayuid-to-postgres
  namespace: kong
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kong
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: postgres-perms